# Generated by Django 5.2 on 2026-04-10 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_environments', '0001_initial'),
        ('api_interfaces', '0002_initial'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTestCaseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_created_testcase_groups', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api_testcases.apitestcasegroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_testcase_groups', to='projects.project')),
            ],
            options={
                'verbose_name': 'Test Case Group',
                'verbose_name_plural': 'Test Case Groups',
                'ordering': ['name'],
                'unique_together': {('name', 'parent', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('P0', 'P0 - Critical'), ('P1', 'P1 - High'), ('P2', 'P2 - Medium'), ('P3', 'P3 - Low')], default='P2', max_length=2)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_created_testcases', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_testcases', to='projects.project')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_testcases', to='api_testcases.apitestcasegroup')),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestCaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('interface_data', models.JSONField()),
                ('sync_fields', models.JSONField(default=list)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('origin_interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_related_steps', to='api_interfaces.apiinterface')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api_testcases.apitestcase')),
            ],
            options={
                'verbose_name': 'Test Case Step',
                'verbose_name_plural': 'Test Case Steps',
                'ordering': ['order'],
                'unique_together': {('testcase', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ApiTestCaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#1890ff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_created_testcase_tags', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_testcase_tags', to='projects.project')),
            ],
            options={
                'verbose_name': 'Test Case Tag',
                'verbose_name_plural': 'Test Case Tags',
                'ordering': ['name'],
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='api_testcases', to='api_testcases.apitestcasetag'),
        ),
        migrations.CreateModel(
            name='ApiTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('error', 'Error')], max_length=20)),
                ('success_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('duration', models.FloatField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('summary', models.JSONField()),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_testcase_reports', to='api_environments.apienvironment')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_executed_testcase_reports', to=settings.AUTH_USER_MODEL)),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_reports', to='api_testcases.apitestcase')),
            ],
            options={
                'verbose_name': 'Test Report',
                'verbose_name_plural': 'Test Reports',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('elapsed', models.FloatField()),
                ('request', models.JSONField()),
                ('response', models.JSONField()),
                ('validators', models.JSONField(default=list)),
                ('extracted_variables', models.JSONField(default=dict)),
                ('attachment', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api_testcases.apitestreport')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_results', to='api_testcases.apitestcasestep')),
            ],
            options={
                'verbose_name': 'Test Report Detail',
                'verbose_name_plural': 'Test Report Details',
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='apitestcase',
            unique_together={('name', 'project')},
        ),
    ]
