# Generated by Django 5.2 on 2026-04-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestcasestep',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
