# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api_testcases', '0002_add_config_to_step'),
    ]
    operations = [
        migrations.AddField(
            model_name='apitestcase',
            name='file_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apitestcasestep',
            name='file_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
