# Generated by Django 5.2 on 2026-07-06 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_environments', '0002_alter_apienvironment_verify_ssl'),
        ('api_interfaces', '0005_add_file_ids'),
        ('api_testcases', '0004_add_file_ids'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInterfaceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('P0', 'P0 - Critical'), ('P1', 'P1 - High'), ('P2', 'P2 - Medium'), ('P3', 'P3 - Low')], default='P2', max_length=2)),
                ('config', models.JSONField(default=dict)),
                ('file_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_created_interface_cases', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_interface_cases', to='api_testcases.apitestcasegroup')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_interface_cases', to='api_interfaces.apiinterface')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_interface_cases', to='projects.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='api_interface_cases', to='api_testcases.apitestcasetag')),
            ],
            options={
                'verbose_name': 'Interface Case',
                'verbose_name_plural': 'Interface Cases',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ApiInterfaceCaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('error', 'Error')], max_length=20)),
                ('success_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('duration', models.FloatField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('summary', models.JSONField()),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_interface_case_reports', to='api_environments.apienvironment')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_executed_interface_case_reports', to=settings.AUTH_USER_MODEL)),
                ('interface_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_reports', to='api_testcases.apiinterfacecase')),
            ],
            options={
                'verbose_name': 'Interface Case Report',
                'verbose_name_plural': 'Interface Case Reports',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiInterfaceCaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('precondition', 'Precondition'), ('main', 'Main Interface')], default='precondition', max_length=20)),
                ('order', models.IntegerField()),
                ('interface_data', models.JSONField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('file_ids', models.JSONField(blank=True, default=list)),
                ('sync_fields', models.JSONField(default=list)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('interface_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api_testcases.apiinterfacecase')),
                ('origin_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_interface_case_steps', to='api_interfaces.apiinterface')),
            ],
            options={
                'verbose_name': 'Interface Case Step',
                'verbose_name_plural': 'Interface Case Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ApiInterfaceCaseReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('elapsed', models.FloatField()),
                ('request', models.JSONField()),
                ('response', models.JSONField()),
                ('validators', models.JSONField(default=list)),
                ('extracted_variables', models.JSONField(default=dict)),
                ('attachment', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api_testcases.apiinterfacecasereport')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_results', to='api_testcases.apiinterfacecasestep')),
            ],
            options={
                'verbose_name': 'Interface Case Report Detail',
                'verbose_name_plural': 'Interface Case Report Details',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='apiinterfacecasestep',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'main')), fields=('interface_case',), name='unique_main_step_per_interface_case'),
        ),
        migrations.AlterUniqueTogether(
            name='apiinterfacecasestep',
            unique_together={('interface_case', 'order')},
        ),
    ]
