# Generated by Django 5.2 on 2026-04-10 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_interfaces', '0002_initial'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto'), ('batch', 'Batch')], max_length=20, verbose_name='Sync Type')),
                ('sync_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20, verbose_name='Sync Status')),
                ('sync_fields', models.JSONField(verbose_name='Sync Fields')),
                ('old_data', models.JSONField(verbose_name='Old Data')),
                ('new_data', models.JSONField(verbose_name='New Data')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('sync_time', models.DateTimeField(auto_now_add=True, verbose_name='Sync Time')),
            ],
            options={
                'verbose_name': 'API Sync History',
                'verbose_name_plural': 'API Sync Histories',
                'ordering': ['-sync_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiGlobalSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sync_fields', models.JSONField(default=list, help_text='List of fields to synchronize.', verbose_name='Sync Fields')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('sync_mode', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=20, verbose_name='Sync Mode')),
                ('is_active', models.BooleanField(default=False, help_text='Only one config may be active per project.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_created_global_sync_configs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_global_sync_configs', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'API Global Sync Config',
                'verbose_name_plural': 'API Global Sync Configs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sync_fields', models.JSONField(default=list, help_text='List of fields to synchronize.', verbose_name='Sync Fields')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('sync_mode', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=20, verbose_name='Sync Mode')),
                ('sync_trigger', models.JSONField(default=dict, help_text='Trigger conditions for auto sync.', verbose_name='Trigger Conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_created_sync_configs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_sync_configs', to='api_interfaces.apiinterface', verbose_name='Interface')),
            ],
            options={
                'verbose_name': 'API Sync Config',
                'verbose_name_plural': 'API Sync Configs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
