# Generated by Django 5.2 on 2026-04-10 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_sync', '0001_initial'),
        ('api_testcases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apisyncconfig',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_sync_configs', to='api_testcases.apitestcasestep', verbose_name='Step'),
        ),
        migrations.AddField(
            model_name='apisyncconfig',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_sync_configs', to='api_testcases.apitestcase', verbose_name='Test Case'),
        ),
        migrations.AddField(
            model_name='apisynchistory',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AddField(
            model_name='apisynchistory',
            name='sync_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_sync_histories', to='api_sync.apisyncconfig', verbose_name='Sync Config'),
        ),
        migrations.AlterUniqueTogether(
            name='apiglobalsyncconfig',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='apisyncconfig',
            unique_together={('interface', 'testcase', 'step')},
        ),
    ]
