# Generated by Django 5.2.1 on 2025-05-19 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='用例名称')),
                ('precondition', models.TextField(blank=True, null=True, verbose_name='前置描述')),
                ('level', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P2', max_length=2, verbose_name='用例等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_testcases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '用例',
                'verbose_name_plural': '用例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='步骤编号')),
                ('description', models.TextField(verbose_name='步骤描述')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_testcase_steps', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='testcases.testcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '用例步骤',
                'verbose_name_plural': '用例步骤',
                'ordering': ['test_case', 'step_number'],
                'unique_together': {('test_case', 'step_number')},
            },
        ),
    ]
