# Generated by Django 5.2 on 2025-05-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0002_testcasemodule"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="testcases",
                to="testcases.testcasemodule",
                verbose_name="所属模块",
            ),
        ),
    ]
