# Generated by Django 5.2 on 2025-05-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0003_testcase_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
    ]
