# Generated by Django 5.2 on 2025-06-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testcases", "0004_testcase_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="screenshot",
            field=models.ImageField(
                blank=True,
                help_text="测试用例的截屏图片",
                null=True,
                upload_to="testcase_screenshots/",
                verbose_name="截屏图片",
            ),
        ),
    ]
