# Generated by Django 5.2 on 2025-06-13 09:57

import django.db.models.deletion
import testcases.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testcases", "0005_testcase_screenshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCaseScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        help_text="测试用例的截屏图片",
                        upload_to=testcases.models.testcase_screenshot_path,
                        verbose_name="截屏图片",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="图片标题"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="图片描述"),
                ),
                (
                    "step_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="对应步骤"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "mcp_session_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="MCP会话ID"
                    ),
                ),
                (
                    "page_url",
                    models.URLField(blank=True, null=True, verbose_name="页面URL"),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="testcases.testcase",
                        verbose_name="测试用例",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_screenshots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传人",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例截屏",
                "verbose_name_plural": "测试用例截屏",
                "ordering": ["test_case", "step_number", "created_at"],
            },
        ),
    ]
