# Generated by Django 5.2 on 2025-08-22 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testcases", "0006_testcasescreenshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="testcases",
                to="testcases.testcasemodule",
                verbose_name="所属模块",
            ),
        ),
    ]
