# Generated by Django 5.2 on 2025-10-23 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_creator'),
        ('testcases', '0007_make_module_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='套件名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='套件描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_suites', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='projects.project', verbose_name='所属项目')),
                ('testcases', models.ManyToManyField(related_name='test_suites', to='testcases.testcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总用例数')),
                ('passed_count', models.PositiveIntegerField(default=0, verbose_name='通过数')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='跳过数')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='错误数')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='任务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testcases.testsuite', verbose_name='测试套件')),
            ],
            options={
                'verbose_name': '测试执行记录',
                'verbose_name_plural': '测试执行记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('pass', '通过'), ('fail', '失败'), ('skip', '跳过'), ('error', '错误')], default='pending', max_length=20, verbose_name='执行状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('stack_trace', models.TextField(blank=True, null=True, verbose_name='堆栈跟踪')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='执行耗时(秒)')),
                ('mcp_session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='MCP会话ID')),
                ('screenshots', models.JSONField(blank=True, default=list, verbose_name='截图列表')),
                ('execution_log', models.TextField(blank=True, null=True, verbose_name='执行日志')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_results', to='testcases.testcase', verbose_name='测试用例')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testcases.testexecution', verbose_name='测试执行')),
            ],
            options={
                'verbose_name': '测试用例执行结果',
                'verbose_name_plural': '测试用例执行结果',
                'ordering': ['execution', 'created_at'],
                'unique_together': {('execution', 'testcase')},
            },
        ),
    ]
