# Generated by Django 5.2 on 2025-10-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0008_testsuite_testexecution_testcaseresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='max_concurrent_tasks',
            field=models.PositiveSmallIntegerField(default=1, help_text='同时执行的测试用例数量，1表示串行执行，建议值2-5', verbose_name='最大并发数'),
        ),
    ]
