# Generated by Django 5.2 on 2025-12-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0009_add_concurrent_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasescreenshot',
            name='page_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='页面URL'),
        ),
    ]
