# Generated by Django 5.2 on 2025-12-10 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_integration', '0007_change_max_steps_default_500'),
        ('testcases', '0010_alter_testcasescreenshot_page_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='脚本名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='脚本描述')),
                ('script_type', models.CharField(choices=[('playwright_python', 'Playwright Python'), ('playwright_javascript', 'Playwright JavaScript')], default='playwright_python', max_length=30, verbose_name='脚本类型')),
                ('source', models.CharField(choices=[('ai_generated', 'AI 自动生成'), ('manual', '手动编写'), ('recorded', '录制生成')], default='ai_generated', max_length=20, verbose_name='来源')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('deprecated', '已废弃')], default='active', max_length=20, verbose_name='状态')),
                ('script_content', models.TextField(verbose_name='脚本代码')),
                ('recorded_steps', models.JSONField(blank=True, default=list, help_text='从 AgentStep 提取的 Playwright 操作列表', verbose_name='记录的操作步骤')),
                ('target_url', models.URLField(blank=True, max_length=2000, null=True, verbose_name='目标URL')),
                ('timeout_seconds', models.IntegerField(default=30, verbose_name='超时时间(秒)')),
                ('headless', models.BooleanField(default=True, verbose_name='无头模式')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automation_scripts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_scripts', to='orchestrator_integration.agenttask', verbose_name='来源任务')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_scripts', to='testcases.testcase', verbose_name='关联功能用例')),
            ],
            options={
                'verbose_name': '自动化用例',
                'verbose_name_plural': '自动化用例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('error', '错误'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='执行耗时(秒)')),
                ('output', models.TextField(blank=True, null=True, verbose_name='执行输出')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('stack_trace', models.TextField(blank=True, null=True, verbose_name='堆栈跟踪')),
                ('screenshots', models.JSONField(blank=True, default=list, verbose_name='截图列表')),
                ('browser_type', models.CharField(default='chromium', max_length=50, verbose_name='浏览器类型')),
                ('viewport', models.JSONField(blank=True, default=dict, verbose_name='视口大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testcases.automationscript', verbose_name='执行的脚本')),
            ],
            options={
                'verbose_name': '脚本执行记录',
                'verbose_name_plural': '脚本执行记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
