# Generated by Django 5.2 on 2025-12-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0011_automationscript_scriptexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptexecution',
            name='videos',
            field=models.JSONField(blank=True, default=list, verbose_name='录屏列表'),
        ),
    ]
