# Generated by Django 5.2 on 2025-12-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0012_add_videos_to_script_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='automation_scripts',
            field=models.ManyToManyField(blank=True, help_text='关联的 Playwright 自动化测试脚本', related_name='test_suites', to='testcases.automationscript', verbose_name='自动化脚本'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='max_concurrent_tasks',
            field=models.PositiveSmallIntegerField(default=1, help_text='同时执行的测试用例/脚本数量，1表示串行执行，建议值2-5', verbose_name='最大并发数'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='testcases',
            field=models.ManyToManyField(blank=True, related_name='test_suites', to='testcases.testcase', verbose_name='测试用例'),
        ),
    ]
