# Generated by Django 5.2 on 2025-12-11 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0013_add_automation_scripts_to_testsuite'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptexecution',
            name='test_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='script_results', to='testcases.testexecution', verbose_name='测试执行'),
        ),
    ]
