# Generated by Django 5.2 on 2025-12-11 17:26

from django.db import migrations, models


def update_status_values(apps, schema_editor):
    """更新现有数据中的状态值: passed -> pass, failed -> fail"""
    ScriptExecution = apps.get_model('testcases', 'ScriptExecution')
    ScriptExecution.objects.filter(status='passed').update(status='pass')
    ScriptExecution.objects.filter(status='failed').update(status='fail')


def reverse_status_values(apps, schema_editor):
    """回滚状态值: pass -> passed, fail -> failed"""
    ScriptExecution = apps.get_model('testcases', 'ScriptExecution')
    ScriptExecution.objects.filter(status='pass').update(status='passed')
    ScriptExecution.objects.filter(status='fail').update(status='failed')


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0014_scriptexecution_test_execution'),
    ]

    operations = [
        # 先更新现有数据
        migrations.RunPython(update_status_values, reverse_status_values),
        # 再修改字段的 choices
        migrations.AlterField(
            model_name='scriptexecution',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('pass', '通过'), ('fail', '失败'), ('error', '错误'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态'),
        ),
    ]
