# Generated by Django 5.2 on 2025-12-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0015_update_script_execution_status_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='generate_playwright_script',
            field=models.BooleanField(default=False, help_text='执行功能测试用例时是否自动生成Playwright脚本', verbose_name='生成脚本'),
        ),
    ]
