# Generated by Django 5.2 on 2026-01-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0017_testcase_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='review_status',
            field=models.CharField(blank=True, choices=[('pending_review', '待审核'), ('approved', '通过'), ('needs_optimization', '优化'), ('optimization_pending_review', '优化待审核'), ('unavailable', '不可用')], default='pending_review', max_length=30, null=True, verbose_name='审核状态'),
        ),
    ]
