# Generated by Django 5.2 on 2026-01-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0018_alter_testcase_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptexecution',
            name='script',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='automation_scripts',
        ),
        migrations.RemoveField(
            model_name='scriptexecution',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='scriptexecution',
            name='test_execution',
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='max_concurrent_tasks',
            field=models.PositiveSmallIntegerField(default=1, help_text='同时执行的测试用例数量，1表示串行执行，建议值2-5', verbose_name='最大并发数'),
        ),
        migrations.DeleteModel(
            name='AutomationScript',
        ),
        migrations.DeleteModel(
            name='ScriptExecution',
        ),
    ]
