# Generated by Django 5.2 on 2026-02-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0019_remove_automation_scripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test_type',
            field=models.CharField(blank=True, choices=[('smoke', '冒烟测试'), ('functional', '功能测试'), ('boundary', '边界测试'), ('exception', '异常测试'), ('permission', '权限测试'), ('security', '安全测试'), ('compatibility', '兼容性测试')], default='functional', max_length=20, verbose_name='测试类型'),
        ),
    ]
