# Generated by Django 5.2 on 2026-05-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0020_add_test_type_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcasemodule',
            options={'ordering': ['project', 'level', 'order', 'id'], 'verbose_name': '用例模块', 'verbose_name_plural': '用例模块'},
        ),
        migrations.AddField(
            model_name='testcasemodule',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
