# Generated by Django 5.2 on 2026-01-07 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('import', '导入'), ('export', '导出'), ('both', '导入/导出')], default='import', max_length=10, verbose_name='模板类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模板描述')),
                ('sheet_name', models.CharField(blank=True, help_text='为空则默认使用第一个工作表', max_length=255, null=True, verbose_name='工作表名称')),
                ('header_row', models.PositiveIntegerField(default=1, help_text='Excel中字段名所在行(从1开始)', verbose_name='表头行号')),
                ('data_start_row', models.PositiveIntegerField(default=2, help_text='数据从第几行开始(从1开始)，支持表头和数据之间有空行', verbose_name='数据起始行号')),
                ('field_mappings', models.JSONField(blank=True, default=dict, help_text='内部字段名到Excel列名的映射，如 {"name": "用例名称", "level": "优先级"}', verbose_name='字段映射')),
                ('value_transformations', models.JSONField(blank=True, default=dict, help_text='字段值转换规则，如 {"level": {"高": "P0", "中": "P1", "低": "P2"}}', verbose_name='值转换规则')),
                ('step_parsing_mode', models.CharField(choices=[('single_cell', '单元格合并步骤'), ('multi_row', '多行步骤')], default='single_cell', max_length=20, verbose_name='步骤解析模式')),
                ('step_config', models.JSONField(blank=True, default=dict, help_text='步骤解析的详细配置，包括列名和格式模式', verbose_name='步骤解析配置')),
                ('module_path_delimiter', models.CharField(default='/', help_text='Excel中模块路径的分隔符，如 "/" 或 ">"', max_length=10, verbose_name='模块路径分隔符')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_import_export_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '用例导入导出模板',
                'verbose_name_plural': '用例导入导出模板',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['is_active', 'template_type'], name='testcase_te_is_acti_a8ee95_idx'), models.Index(fields=['name'], name='testcase_te_name_439000_idx')],
            },
        ),
    ]
