# Generated by Django 5.1.4 on 2025-05-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for the LLM configuration.', max_length=255, unique=True)),
                ('api_url', models.URLField(help_text='The API endpoint URL for the LLM.')),
                ('api_key', models.CharField(help_text='The API key for accessing the LLM.', max_length=512)),
                ('is_active', models.BooleanField(default=False, help_text='Indicates if this LLM configuration is currently active. Only one can be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Configuration',
                'verbose_name_plural': 'LLM Configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
