# Generated by Django 5.2 on 2025-05-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langgraph_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconfig",
            name="system_prompt",
            field=models.TextField(
                blank=True,
                help_text="System prompt to guide the LLM's behavior. This will be added as the first message in conversations.",
                null=True,
            ),
        ),
    ]
