# Generated by Django 5.2 on 2025-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("langgraph_integration", "0002_llmconfig_system_prompt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="llmconfig",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "LLM配置",
                "verbose_name_plural": "LLM配置",
            },
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="config_name",
            field=models.CharField(
                default="默认配置",
                help_text="用户自定义的配置名称，如'生产环境OpenAI'、'测试Claude配置'",
                max_length=255,
                verbose_name="配置名称",
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="api_key",
            field=models.CharField(
                help_text="访问LLM服务的API密钥", max_length=512, verbose_name="API密钥"
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="api_url",
            field=models.URLField(help_text="LLM服务的API端点URL", verbose_name="API地址"),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="是否为当前激活的LLM配置", verbose_name="是否激活"
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="name",
            field=models.CharField(
                help_text="具体的模型名称，如 gpt-4, claude-3-sonnet, gpt-3.5-turbo",
                max_length=255,
                verbose_name="模型名称",
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="system_prompt",
            field=models.TextField(
                blank=True, help_text="指导LLM行为的系统级提示词", null=True, verbose_name="系统提示词"
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
