# Generated by Django 5.2 on 2025-08-05 10:04

from django.db import migrations


def update_config_names(apps, schema_editor):
    """为现有记录设置唯一的 config_name"""
    LLMConfig = apps.get_model('langgraph_integration', 'LLMConfig')
    
    # 为每个现有记录设置唯一的 config_name
    for i, config in enumerate(LLMConfig.objects.all(), 1):
        if config.config_name == "默认配置" or not config.config_name:
            # 基于模型名称和序号生成唯一名称
            config.config_name = f"{config.name}_配置_{i}"
            config.save()


def reverse_update_config_names(apps, schema_editor):
    """回滚操作"""
    LLMConfig = apps.get_model('langgraph_integration', 'LLMConfig')
    LLMConfig.objects.all().update(config_name="默认配置")


class Migration(migrations.Migration):
    dependencies = [
        ("langgraph_integration", "0003_add_config_name_field"),
    ]

    operations = [
        migrations.RunPython(update_config_names, reverse_update_config_names),
    ]
