# Generated by Django 5.2 on 2025-08-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("langgraph_integration", "0004_update_config_name_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmconfig",
            name="config_name",
            field=models.CharField(
                help_text="用户自定义的配置名称，如'生产环境OpenAI'、'测试Claude配置'",
                max_length=255,
                unique=True,
                verbose_name="配置名称",
            ),
        ),
    ]
