# Generated by Django 5.2 on 2025-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("langgraph_integration", "0005_add_config_name_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconfig",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic/Claude"),
                    ("openai_compatible", "OpenAI Compatible (Ollama, etc.)"),
                ],
                default="openai",
                help_text="LLM服务供应商",
                max_length=50,
                verbose_name="供应商",
            ),
        ),
    ]
