# Generated by Django 5.2 on 2025-08-22 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("langgraph_integration", "0006_llmconfig_provider"),
        ("projects", "0002_project_creator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmconfig",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic/Claude"),
                    ("gemini", "Google Gemini"),
                    ("qwen", "Alibaba Qwen"),
                    ("ollama", "Ollama"),
                    ("openai_compatible", "OpenAI Compatible"),
                ],
                default="openai",
                help_text="LLM服务供应商",
                max_length=50,
                verbose_name="供应商",
            ),
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="LangGraph会话的唯一标识符",
                        max_length=255,
                        unique=True,
                        verbose_name="会话ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="新对话", max_length=200, verbose_name="对话标题"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="关联项目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "对话会话",
                "verbose_name_plural": "对话会话",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        help_text="LangGraph消息的唯一标识符",
                        max_length=255,
                        verbose_name="消息ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "用户"), ("assistant", "助手"), ("system", "系统")],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="langgraph_integration.chatsession",
                        verbose_name="对话会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "对话消息",
                "verbose_name_plural": "对话消息",
                "ordering": ["created_at"],
            },
        ),
    ]
