# Generated by Django 5.2 on 2025-11-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0007_alter_llmconfig_provider_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='supports_vision',
            field=models.BooleanField(default=False, help_text='模型是否支持图片/多模态输入（如GPT-4V、Qwen-VL等）', verbose_name='支持图片输入'),
        ),
    ]
