# Generated by Django 5.2 on 2025-11-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0008_llmconfig_supports_vision'),
        ('prompts', '0007_remove_userprompt_unique_user_program_prompt_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='prompt',
            field=models.ForeignKey(blank=True, help_text='该会话使用的提示词', null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompts.userprompt', verbose_name='关联提示词'),
        ),
    ]
