# Generated by Django 5.2 on 2025-12-01 07:52

from django.db import migrations, models


def migrate_old_providers(apps, schema_editor):
    """将旧的 provider 值迁移到新的简化选项"""
    LLMConfig = apps.get_model('langgraph_integration', 'LLMConfig')
    # openai, ollama, qwen 都使用 OpenAI 兼容格式
    LLMConfig.objects.filter(provider__in=['openai', 'ollama', 'qwen']).update(provider='openai_compatible')


def reverse_migrate(apps, schema_editor):
    """回滚：无法恢复原始值，保持为 openai_compatible"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0009_add_prompt_to_chatsession'),
    ]

    operations = [
        # 先进行数据迁移
        migrations.RunPython(migrate_old_providers, reverse_migrate),
        # 然后修改字段选项
        migrations.AlterField(
            model_name='llmconfig',
            name='provider',
            field=models.CharField(choices=[('openai_compatible', 'OpenAI 兼容'), ('anthropic', 'Anthropic/Claude'), ('gemini', 'Google Gemini')], default='openai_compatible', help_text='LLM服务供应商', max_length=50, verbose_name='供应商'),
        ),
    ]
