# Generated by Django 5.2 on 2025-12-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0011_add_context_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='context_limit',
            field=models.IntegerField(default=128000, help_text='模型最大上下文Token数（GPT-4o: 128000, Claude: 200000, Gemini: 1000000）', verbose_name='上下文限制'),
        ),
    ]
