# Generated by Django 5.2 on 2025-12-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0012_change_context_limit_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='provider',
            field=models.CharField(choices=[('openai_compatible', 'OpenAI 兼容')], default='openai_compatible', help_text='LLM服务供应商', max_length=50, verbose_name='供应商'),
        ),
    ]
