# Generated by Django 5.2 on 2026-01-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0013_alter_llmconfig_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='访问LLM服务的API密钥（可选）', max_length=512, verbose_name='API密钥'),
        ),
    ]
