# Generated by Django 5.2 on 2026-01-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0014_make_api_key_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='enable_hitl',
            field=models.BooleanField(default=False, help_text='启用后，执行高风险操作（如自动化脚本）前需用户确认（需配合HumanInTheLoopMiddleware）', verbose_name='启用人工审批'),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='enable_summarization',
            field=models.BooleanField(default=True, help_text='启用后，当对话Token超过阈值时自动压缩上下文（需配合SummarizationMiddleware）', verbose_name='启用上下文摘要'),
        ),
    ]
