# Generated by Django 5.2 on 2026-01-15 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0015_add_middleware_config_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToolApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(help_text='需要审批的工具名称，如 execute_script, run_playwright', max_length=100, verbose_name='工具名称')),
                ('policy', models.CharField(choices=[('always_allow', '始终允许'), ('always_reject', '始终拒绝'), ('ask_every_time', '每次询问')], default='ask_every_time', max_length=20, verbose_name='审批策略')),
                ('scope', models.CharField(choices=[('session', '仅本次会话'), ('permanent', '永久生效')], default='permanent', max_length=20, verbose_name='生效范围')),
                ('session_id', models.CharField(blank=True, help_text="当 scope='session' 时，仅在此会话内生效", max_length=255, null=True, verbose_name='会话ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_approvals', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户工具审批偏好',
                'verbose_name_plural': '用户工具审批偏好',
                'indexes': [models.Index(fields=['user', 'tool_name'], name='langgraph_i_user_id_486ca0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tool_name', 'scope', 'session_id'), name='unique_user_tool_approval')],
            },
        ),
    ]
