# Generated by Django 5.2 on 2026-01-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0016_add_user_tool_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='enable_hitl',
            field=models.BooleanField(default=True, help_text='启用后，执行高风险操作（如自动化脚本）前需用户确认（需配合HumanInTheLoopMiddleware）', verbose_name='启用人工审批'),
        ),
    ]
