# Generated by Django 5.2 on 2026-01-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0017_change_enable_hitl_default_to_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='enable_streaming',
            field=models.BooleanField(default=True, help_text='启用后，AI回复将以流式方式逐字输出；禁用则等待完整回复后一次性返回', verbose_name='启用流式输出'),
        ),
    ]
