# Generated by Django 5.2 on 2026-01-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0018_add_enable_streaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='request_count',
            field=models.IntegerField(default=0, help_text='该会话的 LLM 请求次数', verbose_name='请求次数'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_input_tokens',
            field=models.BigIntegerField(default=0, help_text='该会话累计消耗的输入 Token 数', verbose_name='累计输入 Token'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_output_tokens',
            field=models.BigIntegerField(default=0, help_text='该会话累计消耗的输出 Token 数', verbose_name='累计输出 Token'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_tokens',
            field=models.BigIntegerField(default=0, help_text='该会话累计消耗的总 Token 数（输入+输出）', verbose_name='累计总 Token'),
        ),
    ]
