# Generated by Django 5.2 on 2026-01-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0019_add_token_usage_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='max_retries',
            field=models.IntegerField(default=2, help_text='请求失败时的自动重试次数，默认2次。设为0禁用重试', verbose_name='最大重试次数'),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='request_timeout',
            field=models.IntegerField(default=120, help_text='单次LLM请求的超时时间，默认120秒。如果模型响应较慢可适当增加', verbose_name='请求超时(秒)'),
        ),
    ]
