# Generated by Django 5.2 on 2026-02-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0020_add_timeout_retry_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='max_retries',
            field=models.IntegerField(default=3, help_text='请求失败时的自动重试次数，默认3次。设为0禁用重试', verbose_name='最大重试次数'),
        ),
    ]
