# Generated by Django 5.2 on 2026-04-14 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0022_alter_llmconfig_provider'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='total_cache_read_tokens',
            field=models.BigIntegerField(default=0, help_text='该会话累计缓存命中的 Token 数', verbose_name='累计缓存命中 Token'),
        ),
        migrations.CreateModel(
            name='TokenUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='关联的会话标识（非外键）', max_length=255, verbose_name='会话ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='输入 Token')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='输出 Token')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总 Token')),
                ('cache_read_tokens', models.IntegerField(default=0, verbose_name='缓存命中 Token')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='关联项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Token 使用记录',
                'verbose_name_plural': 'Token 使用记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='langgraph_i_user_id_6bb484_idx'), models.Index(fields=['created_at'], name='langgraph_i_created_30561a_idx')],
            },
        ),
    ]
