# Generated by Django 5.2 on 2026-05-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0024_backfill_token_usage_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='provider',
            field=models.CharField(choices=[('openai_compatible', 'OpenAI 兼容'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen/通义千问')], default='openai_compatible', help_text='LLM服务供应商', max_length=50, verbose_name='供应商'),
        ),
    ]
