# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('langgraph_integration', '0026_restore_llmconfig_table_if_missing'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE langgraph_integration_chatsession
                    ADD COLUMN IF NOT EXISTS resolved_module_key varchar(64) NOT NULL DEFAULT 'llm_chat';
                    ALTER TABLE langgraph_integration_chatsession
                    ALTER COLUMN resolved_module_key SET DEFAULT 'llm_chat';

                    ALTER TABLE langgraph_integration_chatsession
                    ADD COLUMN IF NOT EXISTS resolved_source varchar(32) NOT NULL DEFAULT 'legacy';
                    ALTER TABLE langgraph_integration_chatsession
                    ALTER COLUMN resolved_source SET DEFAULT 'legacy';

                    ALTER TABLE langgraph_integration_chatsession
                    ADD COLUMN IF NOT EXISTS resolved_bundle_id bigint NULL;

                    ALTER TABLE langgraph_integration_chatsession
                    ADD COLUMN IF NOT EXISTS resolved_runtime_mode varchar(16) NOT NULL DEFAULT 'auto';
                    ALTER TABLE langgraph_integration_chatsession
                    ALTER COLUMN resolved_runtime_mode SET DEFAULT 'auto';
                    """,
                    reverse_sql="""
                    ALTER TABLE langgraph_integration_chatsession DROP COLUMN IF EXISTS resolved_runtime_mode;
                    ALTER TABLE langgraph_integration_chatsession DROP COLUMN IF EXISTS resolved_bundle_id;
                    ALTER TABLE langgraph_integration_chatsession DROP COLUMN IF EXISTS resolved_source;
                    ALTER TABLE langgraph_integration_chatsession DROP COLUMN IF EXISTS resolved_module_key;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='chatsession',
                    name='resolved_module_key',
                    field=models.CharField(default='llm_chat', max_length=64, verbose_name='解析模块Key'),
                ),
                migrations.AddField(
                    model_name='chatsession',
                    name='resolved_source',
                    field=models.CharField(default='legacy', max_length=32, verbose_name='LLM配置来源'),
                ),
                migrations.AddField(
                    model_name='chatsession',
                    name='resolved_bundle_id',
                    field=models.BigIntegerField(blank=True, null=True, verbose_name='解析配置包ID'),
                ),
                migrations.AddField(
                    model_name='chatsession',
                    name='resolved_runtime_mode',
                    field=models.CharField(default='auto', max_length=16, verbose_name='运行模式'),
                ),
            ],
        ),
    ]
