# Generated by Django 5.2 on 2026-04-10 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_database_configs', '0001_initial'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('base_url', models.URLField(verbose_name='Base URL')),
                ('verify_ssl', models.BooleanField(default=True, verbose_name='Verify SSL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_created_environments', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('database_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_environments', to='api_database_configs.apidatabaseconfig', verbose_name='Database Config')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_children', to='api_environments.apienvironment', verbose_name='Parent Environment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_environments', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'API Environment',
                'verbose_name_plural': 'API Environments',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ApiEnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.TextField(verbose_name='Value')),
                ('type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('list', 'List'), ('dict', 'Dict')], default='string', max_length=20, verbose_name='Type')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='Sensitive')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_variables', to='api_environments.apienvironment', verbose_name='Environment')),
            ],
            options={
                'verbose_name': 'API Environment Variable',
                'verbose_name_plural': 'API Environment Variables',
                'ordering': ['name'],
                'unique_together': {('environment', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ApiGlobalRequestHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Header Name')),
                ('value', models.TextField(verbose_name='Header Value')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_created_headers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_global_headers', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'API Global Request Header',
                'verbose_name_plural': 'API Global Request Headers',
                'ordering': ['name'],
                'unique_together': {('name', 'project')},
            },
        ),
    ]
