# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_environments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apienvironment',
            name='verify_ssl',
            field=models.BooleanField(default=False, verbose_name='Verify SSL'),
        ),
    ]
