# Generated by Django 5.2 on 2025-06-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebase",
            name="vector_store_type",
            field=models.CharField(
                choices=[("chroma", "ChromaDB")],
                default="chroma",
                max_length=50,
                verbose_name="向量存储类型",
            ),
        ),
    ]
