# Generated by Django 5.2 on 2025-06-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_remove_non_chroma_vector_stores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebase",
            name="embedding_model",
            field=models.CharField(
                choices=[
                    (
                        "BAAI/bge-large-en-v1.5",
                        "BGE-Large-EN-v1.5 (最佳性能, 1024维, ~1.3GB)",
                    ),
                    ("BAAI/bge-base-en-v1.5", "BGE-Base-EN-v1.5 (平衡选择, 768维, ~440MB)"),
                    ("BAAI/bge-m3", "BGE-M3 (多语言, 1024维, ~2.2GB)"),
                    ("intfloat/e5-large-v2", "E5-Large-v2 (Microsoft, 1024维, ~1.3GB)"),
                    (
                        "sentence-transformers/all-MiniLM-L6-v2",
                        "All-MiniLM-L6-v2 (轻量级, 384维, ~90MB)",
                    ),
                ],
                default="BAAI/bge-large-en-v1.5",
                help_text="推荐使用BGE系列模型获得最佳性能，支持本地运行",
                max_length=100,
                verbose_name="嵌入模型",
            ),
        ),
    ]
