# Generated by Django 5.2 on 2025-06-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_update_embedding_model_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebase",
            name="embedding_model",
            field=models.CharField(
                default="BAAI/bge-m3",
                help_text="BGE-M3: 支持中文+多语言的高性能嵌入模型 (1024维, ~2.2GB)",
                max_length=100,
                verbose_name="嵌入模型",
            ),
        ),
    ]
