# Generated by Django 5.2 on 2025-08-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0004_use_bge_m3_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgebase",
            name="vector_store_type",
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="api_base_url",
            field=models.URLField(
                blank=True,
                help_text="OpenAI/Azure/自定义API的基础URL，如：https://api.openai.com/v1",
                null=True,
                verbose_name="API基础URL",
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="API服务的密钥或Token",
                max_length=500,
                null=True,
                verbose_name="API密钥",
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="api_version",
            field=models.CharField(
                blank=True,
                help_text="Azure OpenAI需要，如：2024-02-15-preview",
                max_length=50,
                null=True,
                verbose_name="API版本",
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="custom_headers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="自定义API需要的额外请求头",
                verbose_name="自定义请求头",
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="deployment_name",
            field=models.CharField(
                blank=True,
                help_text="Azure OpenAI的部署名称",
                max_length=100,
                null=True,
                verbose_name="部署名称",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="embedding_model",
            field=models.CharField(
                choices=[
                    (
                        "openai_text-embedding-3-large",
                        "OpenAI text-embedding-3-large (API, 3072维)",
                    ),
                    (
                        "openai_text-embedding-3-small",
                        "OpenAI text-embedding-3-small (API, 1536维)",
                    ),
                    (
                        "openai_text-embedding-ada-002",
                        "OpenAI text-embedding-ada-002 (API, 1536维)",
                    ),
                    (
                        "azure_text-embedding-3-large",
                        "Azure OpenAI text-embedding-3-large (API, 3072维)",
                    ),
                    (
                        "azure_text-embedding-3-small",
                        "Azure OpenAI text-embedding-3-small (API, 1536维)",
                    ),
                    (
                        "azure_text-embedding-ada-002",
                        "Azure OpenAI text-embedding-ada-002 (API, 1536维)",
                    ),
                    (
                        "ollama_nomic-embed-text",
                        "Ollama nomic-embed-text (本地API, 768维)",
                    ),
                    ("ollama_all-minilm", "Ollama all-minilm (本地API, 384维)"),
                    (
                        "ollama_mxbai-embed-large",
                        "Ollama mxbai-embed-large (本地API, 1024维)",
                    ),
                    ("custom_api", "自定义HTTP嵌入接口"),
                ],
                default="BAAI/bge-m3",
                help_text="选择嵌入模型类型：本地模型、API服务或自定义接口",
                max_length=100,
                verbose_name="嵌入模型",
            ),
        ),
    ]
