# Generated by Django 5.2 on 2025-08-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0005_remove_knowledgebase_vector_store_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgebase",
            name="api_version",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="custom_headers",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="deployment_name",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="embedding_model",
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="embedding_service",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("azure_openai", "Azure OpenAI"),
                    ("ollama", "Ollama"),
                    ("custom", "自定义API"),
                ],
                default="openai",
                help_text="选择嵌入服务提供商",
                max_length=50,
                verbose_name="嵌入服务",
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="model_name",
            field=models.CharField(
                blank=True,
                default="text-embedding-ada-002",
                help_text="具体的嵌入模型名称",
                max_length=100,
                null=True,
                verbose_name="模型名称",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="api_base_url",
            field=models.URLField(
                blank=True,
                help_text="API服务的基础URL，如：https://api.openai.com/v1",
                null=True,
                verbose_name="API基础URL",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="API服务的密钥",
                max_length=500,
                null=True,
                verbose_name="API密钥",
            ),
        ),
    ]
