# Generated by Django 5.2 on 2025-11-27 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_remove_knowledgebase_api_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebase',
            name='api_base_url',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='embedding_service',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='model_name',
        ),
        migrations.CreateModel(
            name='KnowledgeGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_service', models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('ollama', 'Ollama'), ('custom', '自定义API')], default='custom', help_text='选择嵌入服务提供商', max_length=50, verbose_name='嵌入服务')),
                ('api_base_url', models.URLField(blank=True, help_text='API服务的基础URL，如：https://api.openai.com/v1', null=True, verbose_name='API基础URL')),
                ('api_key', models.CharField(blank=True, help_text='API服务的密钥', max_length=500, null=True, verbose_name='API密钥')),
                ('model_name', models.CharField(default='text-embedding-ada-002', help_text='具体的嵌入模型名称', max_length=100, verbose_name='模型名称')),
                ('chunk_size', models.PositiveIntegerField(default=1000, verbose_name='默认分块大小')),
                ('chunk_overlap', models.PositiveIntegerField(default=200, verbose_name='默认分块重叠')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_knowledge_configs', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '知识库全局配置',
                'verbose_name_plural': '知识库全局配置',
            },
        ),
    ]
