# Generated by Django 5.2 on 2025-11-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_remove_knowledgebase_api_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='api_base_url',
            field=models.CharField(blank=True, help_text='API服务的基础URL，如：https://api.openai.com/v1 或 http://localhost:11434', max_length=500, null=True, verbose_name='API基础URL'),
        ),
    ]
