# Generated by Django 5.2 on 2025-12-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_remove_knowledgebase_api_base_url_and_more'),
        ('knowledge', '0007_remove_url_validation'),
    ]

    operations = [
    ]
