# Generated by Django 5.2 on 2025-12-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_merge_20251201_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='api_base_url',
            field=models.CharField(blank=True, help_text='API服务的基础URL，如：https://api.openai.com/v1 或 http://bge-m3:11434', max_length=500, null=True, verbose_name='API基础URL'),
        ),
    ]
