# Generated by Django 5.2 on 2026-01-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_add_excel_and_doc_types'),
    ]

    operations = [
        # 更新 embedding_service 字段选项，恢复 ollama 选项
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='embedding_service',
            field=models.CharField(
                choices=[
                    ('openai', 'OpenAI'),
                    ('azure_openai', 'Azure OpenAI'),
                    ('ollama', 'Ollama'),
                    ('xinference', 'Xinference'),
                    ('custom', '自定义API'),
                ],
                default='custom',
                help_text='选择嵌入服务提供商',
                max_length=50,
                verbose_name='嵌入服务'
            ),
        ),
        # 添加 Reranker 服务字段
        migrations.AddField(
            model_name='knowledgeglobalconfig',
            name='reranker_service',
            field=models.CharField(
                choices=[
                    ('none', '不启用'),
                    ('xinference', 'Xinference'),
                    ('custom', '自定义API'),
                ],
                default='none',
                help_text='选择Reranker精排服务，可独立于嵌入服务配置',
                max_length=50,
                verbose_name='Reranker服务'
            ),
        ),
        # 添加 Reranker API 地址字段
        migrations.AddField(
            model_name='knowledgeglobalconfig',
            name='reranker_api_url',
            field=models.CharField(
                blank=True,
                help_text='Reranker服务的API地址，如：http://xinference:9997',
                max_length=500,
                null=True,
                verbose_name='Reranker API地址'
            ),
        ),
        # 添加 Reranker 模型名称字段
        migrations.AddField(
            model_name='knowledgeglobalconfig',
            name='reranker_model_name',
            field=models.CharField(
                default='bge-reranker-v2-m3',
                help_text='Reranker模型名称',
                max_length=100,
                verbose_name='Reranker模型名称'
            ),
        ),
    ]
