# Generated by Django 5.2 on 2026-01-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0011_add_reranker_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeglobalconfig',
            name='reranker_api_key',
            field=models.CharField(
                blank=True,
                help_text='Reranker服务的API密钥（自定义API可能需要）',
                max_length=500,
                null=True,
                verbose_name='Reranker API密钥'
            ),
        ),
    ]
