# Generated by Django 5.2 on 2026-01-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0012_add_reranker_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='api_base_url',
            field=models.CharField(blank=True, help_text='API服务的基础URL，如：https://api.openai.com/v1 或 http://xinference:9997', max_length=500, null=True, verbose_name='API基础URL'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='reranker_model_name',
            field=models.CharField(blank=True, default='bge-reranker-v2-m3', help_text='Reranker模型名称', max_length=100, verbose_name='Reranker模型名称'),
        ),
    ]
