# Generated by Django 5.2 on 2026-02-06 11:28

import django.db.models.deletion
import knowledge.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0013_alter_knowledgeglobalconfig_api_base_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=knowledge.models.document_image_upload_path, verbose_name='图片文件')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='所在页码')),
                ('image_index', models.PositiveIntegerField(default=0, verbose_name='图片序号')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='宽度(px)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='高度(px)')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('caption', models.TextField(blank=True, default='', verbose_name='图片说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='knowledge.document', verbose_name='所属文档')),
            ],
            options={
                'verbose_name': '文档图片',
                'verbose_name_plural': '文档图片',
                'ordering': ['document', 'page_number', 'image_index'],
            },
        ),
    ]
