# Generated by Django 5.2 on 2026-02-09 02:00

import knowledge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0014_add_document_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=knowledge.models.document_image_upload_path, verbose_name='图片文件'),
        ),
    ]
