# Generated by Django 5.2 on 2026-02-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0015_alter_documentimage_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='model_name',
            field=models.CharField(default='qwen3-vl-emb-2b', help_text='具体的嵌入模型名称', max_length=100, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='reranker_model_name',
            field=models.CharField(blank=True, default='Qwen3-VL-Reranker-2B', help_text='Reranker模型名称', max_length=100, verbose_name='Reranker模型名称'),
        ),
    ]
