# Generated by Django 5.2 on 2026-04-10 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('sqlite', 'SQLite'), ('oracle', 'Oracle'), ('sqlserver', 'SQL Server')], default='mysql', max_length=20, verbose_name='Database Type')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('port', models.IntegerField(default=3306, verbose_name='Port')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('database', models.CharField(max_length=100, verbose_name='Database Name')),
                ('charset', models.CharField(default='utf8mb4', max_length=50, verbose_name='Charset')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('psm', models.CharField(blank=True, max_length=255, null=True, verbose_name='PSM')),
                ('verify_ssl', models.BooleanField(default=False, verbose_name='Verify SSL')),
                ('connection_params', models.JSONField(blank=True, default=dict, verbose_name='Connection Params')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_created_database_configs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_database_configs', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'API Database Config',
                'verbose_name_plural': 'API Database Configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
