# Generated by Django 5.2 on 2025-11-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='password',
            field=models.CharField(blank=True, help_text='登录密码', max_length=255, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='project',
            name='system_url',
            field=models.URLField(blank=True, help_text='系统访问地址（如 https://test.example.com）', max_length=255, verbose_name='项目地址'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_role',
            field=models.CharField(blank=True, help_text='如"管理员"、"普通用户"、"审核员"等', max_length=50, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='project',
            name='username',
            field=models.CharField(blank=True, help_text='登录账号', max_length=100, verbose_name='用户名'),
        ),
    ]
