# Generated by Django 5.2 on 2025-11-18 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_password_project_system_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='password',
        ),
        migrations.RemoveField(
            model_name='project',
            name='system_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='project',
            name='username',
        ),
        migrations.CreateModel(
            name='ProjectCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_url', models.URLField(blank=True, help_text='系统访问地址（如 https://test.example.com）', max_length=255, verbose_name='项目地址')),
                ('username', models.CharField(blank=True, help_text='登录账号', max_length=100, verbose_name='用户名')),
                ('password', models.CharField(blank=True, help_text='登录密码', max_length=255, verbose_name='密码')),
                ('user_role', models.CharField(blank=True, help_text='如"管理员"、"普通用户"、"审核员"等', max_length=50, verbose_name='角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目凭据',
                'verbose_name_plural': '项目凭据',
                'ordering': ['project', 'user_role'],
            },
        ),
    ]
