# Generated by Django 5.2 on 2026-02-06 03:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, default='', max_length=200, verbose_name='任务描述')),
                ('module', models.CharField(choices=[('ui_automation', 'UI 自动化'), ('ai_data', 'AI造数')], max_length=20, verbose_name='所属模块')),
                ('execution_target', models.CharField(choices=[('actuator', '执行器')], default='actuator', max_length=20, verbose_name='执行目标')),
                ('schedule_type', models.CharField(choices=[('once', '仅执行一次'), ('hourly', '每小时'), ('daily', '每天'), ('weekly', '每周')], max_length=10, verbose_name='调度策略')),
                ('once_datetime', models.DateTimeField(blank=True, null=True, verbose_name='一次性执行时间')),
                ('daily_time', models.TimeField(blank=True, null=True, verbose_name='每日执行时间')),
                ('weekly_days', models.JSONField(blank=True, default=list, help_text='0=周一, 6=周日', verbose_name='每周执行日')),
                ('weekly_time', models.TimeField(blank=True, null=True, verbose_name='每周执行时间')),
                ('hourly_minute', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='每小时第几分钟')),
                ('retry_enabled', models.BooleanField(default=False, verbose_name='启用失败重试')),
                ('retry_count', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='重试次数')),
                ('retry_interval', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='重试间隔(分钟)')),
                ('status', models.CharField(choices=[('disabled', '未启用'), ('running', '运行中'), ('executing', '执行中')], default='disabled', max_length=10, verbose_name='状态')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery任务ID')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最近执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='执行ID')),
                ('trigger_type', models.CharField(choices=[('scheduled', '定时调度'), ('manual', '手动执行'), ('api', 'API 触发')], max_length=10, verbose_name='触发方式')),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='running', max_length=10, verbose_name='状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('log', models.TextField(blank=True, default='', verbose_name='执行日志')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery任务ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='task_center.scheduledtask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '执行记录',
                'verbose_name_plural': '执行记录',
                'ordering': ['-started_at'],
            },
        ),
    ]
