# Generated by Django 5.2 on 2026-02-06 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_center', '0001_initial'),
        ('testcases', '0020_add_test_type_field'),
        ('ui_automation', '0003_add_batch_execution_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='test_suite',
            field=models.ForeignKey(blank=True, help_text='模块为"测试套件"时必填', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='testcases.testsuite', verbose_name='关联测试套件'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='ui_testcases',
            field=models.ManyToManyField(blank=True, help_text='模块为"UI自动化"时选择要执行的用例', related_name='scheduled_tasks', to='ui_automation.uitestcase', verbose_name='关联UI用例'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='module',
            field=models.CharField(choices=[('ui_automation', 'UI 自动化'), ('test_suite', '测试套件')], max_length=20, verbose_name='所属模块'),
        ),
    ]
