# Generated by Django 5.2 on 2026-02-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_center', '0002_scheduledtask_test_suite_scheduledtask_ui_testcases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='actuator_id',
            field=models.CharField(blank=True, default='', help_text='UI自动化模块时选择的执行器', max_length=100, verbose_name='执行器ID'),
        ),
    ]
