# Generated by Django 5.2 on 2026-02-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_center', '0003_scheduledtask_actuator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='status',
            field=models.CharField(choices=[('disabled', '未启用'), ('running', '运行中')], default='disabled', max_length=10, verbose_name='状态'),
        ),
    ]
