# Generated by Django 5.2 on 2025-07-02 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="提示词的显示名称", max_length=255, verbose_name="提示词名称"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="系统提示词的具体内容，将在对话开始时发送给AI", verbose_name="提示词内容"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="提示词的用途和说明", null=True, verbose_name="描述"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="是否为该用户的默认提示词（每个用户只能有一个默认提示词）",
                        verbose_name="默认提示词",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="是否启用此提示词", verbose_name="是否启用"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户提示词",
                "verbose_name_plural": "用户提示词",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_default"],
                        name="prompts_use_user_id_be667c_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="prompts_use_user_id_bc11fa_idx",
                    ),
                ],
                "unique_together": {("user", "name")},
            },
        ),
    ]
