# Generated by Django 5.2 on 2025-07-23 02:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprompt",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("general", "通用对话"),
                    ("document_structure", "文档结构分析"),
                    ("direct_analysis", "直接分析"),
                    ("global_analysis", "全局分析"),
                    ("module_analysis", "模块分析"),
                ],
                default="general",
                help_text="提示词的使用类型",
                max_length=50,
                verbose_name="提示词类型",
            ),
        ),
        migrations.AlterField(
            model_name="userprompt",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="是否为该用户的默认提示词（仅对通用对话类型有效）",
                verbose_name="默认提示词",
            ),
        ),
        migrations.AddIndex(
            model_name="userprompt",
            index=models.Index(
                fields=["user", "prompt_type"], name="prompts_use_user_id_ffd500_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userprompt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "prompt_type__in",
                        [
                            "document_structure",
                            "direct_analysis",
                            "global_analysis",
                            "module_analysis",
                        ],
                    )
                ),
                fields=("user", "prompt_type"),
                name="unique_user_program_prompt_type",
            ),
        ),
    ]
