# Generated by Django 5.2 on 2025-07-29 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0002_userprompt_prompt_type_alter_userprompt_is_default_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userprompt",
            name="unique_user_program_prompt_type",
        ),
        migrations.AlterField(
            model_name="userprompt",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("general", "通用对话"),
                    ("document_structure", "文档结构分析"),
                    ("direct_analysis", "直接分析"),
                    ("global_analysis", "全局分析"),
                    ("module_analysis", "模块分析"),
                    ("consistency_analysis", "一致性分析"),
                ],
                default="general",
                help_text="提示词的使用类型",
                max_length=50,
                verbose_name="提示词类型",
            ),
        ),
        migrations.AddConstraint(
            model_name="userprompt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "prompt_type__in",
                        [
                            "document_structure",
                            "direct_analysis",
                            "global_analysis",
                            "module_analysis",
                            "consistency_analysis",
                        ],
                    )
                ),
                fields=("user", "prompt_type"),
                name="unique_user_program_prompt_type",
            ),
        ),
    ]
