# Generated by Django 5.2 on 2025-11-20 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0006_remove_userprompt_unique_user_program_prompt_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprompt',
            name='unique_user_program_prompt_type',
        ),
        migrations.AlterField(
            model_name='userprompt',
            name='prompt_type',
            field=models.CharField(choices=[('general', '通用对话'), ('completeness_analysis', '完整性分析'), ('consistency_analysis', '一致性分析'), ('testability_analysis', '可测性分析'), ('feasibility_analysis', '可行性分析'), ('clarity_analysis', '清晰度分析'), ('test_case_execution', '测试用例执行'), ('brain_orchestrator', '智能规划')], default='general', help_text='提示词的使用类型', max_length=50, verbose_name='提示词类型'),
        ),
        migrations.AddConstraint(
            model_name='userprompt',
            constraint=models.UniqueConstraint(condition=models.Q(('prompt_type__in', ['completeness_analysis', 'consistency_analysis', 'testability_analysis', 'feasibility_analysis', 'clarity_analysis', 'test_case_execution'])), fields=('user', 'prompt_type'), name='unique_user_program_prompt_type'),
        ),
    ]
