# Generated by Django 5.2 on 2026-02-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0009_remove_brain_orchestrator_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprompt',
            name='prompt_type',
            field=models.CharField(choices=[('general', '通用对话'), ('completeness_analysis', '完整性分析'), ('consistency_analysis', '一致性分析'), ('testability_analysis', '可测性分析'), ('feasibility_analysis', '可行性分析'), ('clarity_analysis', '清晰度分析'), ('logic_analysis', '逻辑分析'), ('test_case_execution', '测试用例执行'), ('diagram_generation', '图表生成')], default='general', help_text='提示词的使用类型', max_length=50, verbose_name='提示词类型'),
        ),
    ]
