# Generated by Django 5.2 on 2026-04-10 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInterfaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_id', models.IntegerField(blank=True, null=True, verbose_name='Environment ID')),
                ('success', models.BooleanField(verbose_name='Success')),
                ('elapsed', models.FloatField(verbose_name='Elapsed (ms)')),
                ('request_data', models.JSONField(verbose_name='Request Info')),
                ('response_data', models.JSONField(verbose_name='Response Info')),
                ('validation_results', models.JSONField(default=list, verbose_name='Validation Results')),
                ('extracted_variables', models.JSONField(default=dict, verbose_name='Extracted Variables')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Interface Result',
                'verbose_name_plural': 'API Interface Results',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Interface Name')),
                ('type', models.CharField(choices=[('http', 'HTTP'), ('sql', 'SQL')], default='http', max_length=20, verbose_name='Interface Type')),
                ('method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=20, null=True, verbose_name='HTTP Method')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='Headers')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Query Params')),
                ('body', models.JSONField(blank=True, default=dict, verbose_name='Request Body')),
                ('sql_method', models.CharField(blank=True, choices=[('fetchone', 'Fetch One'), ('fetchmany', 'Fetch Many'), ('fetchall', 'Fetch All'), ('insert', 'Insert'), ('update', 'Update'), ('delete', 'Delete')], max_length=20, null=True, verbose_name='SQL Method')),
                ('sql', models.TextField(blank=True, null=True, verbose_name='SQL Statement')),
                ('sql_params', models.JSONField(blank=True, default=dict, verbose_name='SQL Params')),
                ('sql_size', models.IntegerField(blank=True, default=10, help_text='Only used for fetchmany method', verbose_name='Fetch Size')),
                ('setup_hooks', models.JSONField(blank=True, default=list, help_text='["${setup_hook_prepare_kwargs($request)}"]', verbose_name='Setup Hooks')),
                ('teardown_hooks', models.JSONField(blank=True, default=list, help_text='["${teardown_hook_sleep_N_secs($response, 2)}"]', verbose_name='Teardown Hooks')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='{"username": "testuser", "password": "123456"}', verbose_name='Variables')),
                ('validators', models.JSONField(blank=True, default=list, help_text='[{"eq": ["status_code", 200]}]', verbose_name='Validators')),
                ('extract', models.JSONField(blank=True, default=dict, help_text='{"token": "body.data.token"}', verbose_name='Extract Variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_interfaces_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'API Interface',
                'verbose_name_plural': 'API Interfaces',
                'ordering': ['-created_at'],
            },
        ),
    ]
