# Generated by Django 5.2 on 2026-04-10 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_interfaces', '0001_initial'),
        ('api_modules', '0001_initial'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinterface',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_interfaces', to='api_modules.apimodule', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='apiinterface',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_interfaces', to='projects.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='apiinterfaceresult',
            name='executed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_interface_results', to=settings.AUTH_USER_MODEL, verbose_name='Executed By'),
        ),
        migrations.AddField(
            model_name='apiinterfaceresult',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_results', to='api_interfaces.apiinterface', verbose_name='Interface'),
        ),
        migrations.AlterUniqueTogether(
            name='apiinterface',
            unique_together={('name', 'project')},
        ),
    ]
