# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_interfaces', '0002_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE api_interfaces_apiinterface
                    ADD COLUMN IF NOT EXISTS extract_meta jsonb NOT NULL DEFAULT '{}'::jsonb;

                    UPDATE api_interfaces_apiinterface
                    SET extract_meta = '{}'::jsonb
                    WHERE extract_meta IS NULL;

                    ALTER TABLE api_interfaces_apiinterface
                    ALTER COLUMN extract_meta SET DEFAULT '{}'::jsonb;
                    """,
                    reverse_sql="""
                    ALTER TABLE api_interfaces_apiinterface
                    DROP COLUMN IF EXISTS extract_meta;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='apiinterface',
                    name='extract_meta',
                    field=models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Metadata for extract variable rules',
                        verbose_name='Extract Metadata',
                    ),
                ),
            ],
        ),
    ]
