# Generated by Codex on 2026-06-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_interfaces', '0003_apiinterface_extract_meta'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE api_interfaces_apiinterface
            ADD COLUMN IF NOT EXISTS extract_meta jsonb NOT NULL DEFAULT '{}'::jsonb;

            UPDATE api_interfaces_apiinterface
            SET extract_meta = '{}'::jsonb
            WHERE extract_meta IS NULL;

            ALTER TABLE api_interfaces_apiinterface
            ALTER COLUMN extract_meta SET DEFAULT '{}'::jsonb;
            """,
            reverse_sql="""
            ALTER TABLE api_interfaces_apiinterface
            ALTER COLUMN extract_meta DROP DEFAULT;
            """,
        ),
    ]
