# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api_interfaces', '0004_extract_meta_database_default'),
    ]
    operations = [
        migrations.AddField(
            model_name='apiinterface',
            name='file_ids',
            field=models.JSONField(blank=True, default=list, help_text='统一文件管理中的附件ID列表', verbose_name='附件 file_id 列表'),
        ),
    ]
