import os
import tempfile
import logging
import importlib.util

from django.shortcuts import get_object_or_404
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from wharttest_django.viewsets import BaseModelViewSet
from wharttest_django.permissions import HasModelPermission
from wharttest_django.api_permissions import (
    IsProjectMemberForResource,
    IsProjectAdminForResource,
)
from wharttest_django.pagination import StandardPagination

from .models import ApiCustomFunction
from .serializers import ApiCustomFunctionSerializer

logger = logging.getLogger(__name__)


class ApiCustomFunctionViewSet(BaseModelViewSet):
    serializer_class = ApiCustomFunctionSerializer
    pagination_class = StandardPagination

    def get_permissions(self):
        if self.action == 'execute':
            return [IsAuthenticated(), HasModelPermission(), IsProjectAdminForResource()]
        return [IsAuthenticated(), HasModelPermission(), IsProjectMemberForResource()]

    def get_queryset(self):
        project_pk = self.kwargs.get('project_pk')
        return ApiCustomFunction.objects.filter(project_id=project_pk)

    def perform_create(self, serializer):
        from projects.models import Project
        project = get_object_or_404(Project, pk=self.kwargs.get('project_pk'))
        serializer.save(created_by=self.request.user, project=project)

    @action(detail=False, methods=['get'])
    def generate_debugtalk(self, request, *args, **kwargs):
        """Generate debugtalk.py file content for httprunner."""
        project_pk = self.kwargs.get('project_pk')
        functions = ApiCustomFunction.objects.filter(
            project_id=project_pk,
            is_active=True,
        ).order_by('name')

        content = [
            '"""',
            'This file is auto-generated by WHartTest.',
            'Please do not modify this file manually.',
            '"""',
            '',
            'import random',
            'import time',
            'import datetime',
            'import hashlib',
            'import json',
            '',
        ]

        for func in functions:
            if func.description:
                content.extend([
                    f'def {func.name}:',
                    f'    """{func.description}"""',
                ])
            content.append(func.code)
            content.append('')

        return Response({'content': '\n'.join(content)})

    @action(detail=False, methods=['post'])
    def execute(self, request, *args, **kwargs):
        """Test-execute a custom function. Requires project admin permission."""
        code = request.data.get('code')
        test_args = request.data.get('test_args', {})

        if not code:
            return Response(
                {'detail': 'The "code" field is required.'},
                status=status.HTTP_400_BAD_REQUEST,
            )

        temp_file = None
        try:
            with tempfile.NamedTemporaryFile(
                mode='w', suffix='.py', delete=False
            ) as f:
                f.write(code)
                temp_file = f.name

            spec = importlib.util.spec_from_file_location("temp_module", temp_file)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)

            func_name = code.split('def ')[1].split('(')[0].strip()
            func = getattr(module, func_name)

            result = func(**test_args) if test_args else func()

            return Response({'result': str(result)})

        except Exception as e:
            return Response(
                {'detail': str(e)},
                status=status.HTTP_400_BAD_REQUEST,
            )
        finally:
            if temp_file and os.path.exists(temp_file):
                os.unlink(temp_file)
