# Generated by Django 5.2 on 2026-01-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiexecutionrecord',
            name='trace_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Trace 解析数据'),
        ),
        migrations.AddField(
            model_name='uiexecutionrecord',
            name='trace_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Trace 文件路径'),
        ),
        migrations.AlterField(
            model_name='uielement',
            name='wait_time',
            field=models.SmallIntegerField(default=0, verbose_name='等待时间（秒）'),
        ),
    ]
