# Generated by Django 5.2 on 2026-01-26 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0002_add_trace_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UiBatchExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='批次名称')),
                ('total_cases', models.IntegerField(default=0, verbose_name='用例总数')),
                ('passed_cases', models.IntegerField(default=0, verbose_name='成功数')),
                ('failed_cases', models.IntegerField(default=0, verbose_name='失败数')),
                ('status', models.SmallIntegerField(choices=[(0, '待执行'), (1, '执行中'), (2, '全部成功'), (3, '部分失败'), (4, '全部失败')], default=0, verbose_name='状态')),
                ('trigger_type', models.CharField(choices=[('manual', '手动执行'), ('scheduled', '定时执行'), ('api', 'API 触发')], default='manual', max_length=20, verbose_name='触发类型')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='总时长（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_batch_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'verbose_name': '批量执行记录',
                'verbose_name_plural': '批量执行记录',
                'db_table': 'ui_batch_execution_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='uiexecutionrecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='ui_automation.uibatchexecutionrecord', verbose_name='所属批次'),
        ),
    ]
