# Generated by Django 5.2 on 2026-05-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0003_add_batch_execution_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uimodule',
            options={'ordering': ['project', 'level', 'order', 'id'], 'verbose_name': 'UI 模块', 'verbose_name_plural': 'UI 模块'},
        ),
        migrations.AddField(
            model_name='uimodule',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
