# Generated by Django 5.2 on 2026-06-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0003_add_batch_execution_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='uienvironmentconfig',
            name='db2_config',
            field=models.JSONField(blank=True, null=True, verbose_name='DB2配置'),
        ),
        migrations.AddField(
            model_name='uienvironmentconfig',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('db2', 'DB2')], default='mysql', max_length=20, verbose_name='数据库类型'),
        ),
    ]
