# Generated by Django 5.2 on 2026-06-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0004_alter_uimodule_options_uimodule_order'),
        ('ui_automation', '0005_uienvironmentconfig_db2_config_and_more'),
    ]

    operations = []
