# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ui_automation', '0006_merge_uimodule_order_and_db2_config'),
    ]
    operations = [
        migrations.AddField(
            model_name='uipagesteps',
            name='file_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='附件 file_id 列表'),
        ),
        migrations.AddField(
            model_name='uitestcase',
            name='file_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='附件 file_id 列表'),
        ),
    ]
