# Generated by Django 5.2 on 2026-08-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0020_remove_db2_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uienvironmentconfig',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='uienvironmentconfig',
            name='headless',
        ),
        migrations.RemoveField(
            model_name='uienvironmentconfig',
            name='timeout',
        ),
        migrations.RemoveField(
            model_name='uienvironmentconfig',
            name='viewport_height',
        ),
        migrations.RemoveField(
            model_name='uienvironmentconfig',
            name='viewport_width',
        ),
    ]
