# Generated by Django 5.2 on 2026-03-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weixinloginsession',
            name='raw_account_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
