# Generated by Django 5.2 on 2026-05-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apimodule',
            options={'ordering': ['project', 'level', 'order', 'id'], 'verbose_name': 'API Module', 'verbose_name_plural': 'API Modules'},
        ),
        migrations.AddField(
            model_name='apimodule',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Module Level'),
        ),
        migrations.AddField(
            model_name='apimodule',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
