# Generated by Django 5.2 on 2026-01-05 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='只能包含小写字母、数字和连字符', max_length=64, verbose_name='Skill 名称')),
                ('description', models.TextField(help_text='描述 Skill 的功能和使用场景', max_length=1024, verbose_name='Skill 描述')),
                ('skill_content', models.TextField(blank=True, help_text='SKILL.md 文件的完整内容', verbose_name='SKILL.md 内容')),
                ('skill_path', models.CharField(blank=True, help_text='Skill 文件解压后的存储路径', max_length=500, verbose_name='Skill 存储路径')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skills', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
