# Generated by Django 5.2 on 2026-01-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(help_text='描述 Skill 的功能和使用场景', verbose_name='Skill 描述'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Skill 的唯一标识名称', max_length=255, verbose_name='Skill 名称'),
        ),
    ]
