# Generated by Django 5.2 on 2026-04-10 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_environments', '0001_initial'),
        ('api_testcases', '0001_initial'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTestTaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20, verbose_name='Status')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('total_count', models.IntegerField(default=0, verbose_name='Total Cases')),
                ('success_count', models.IntegerField(default=0, verbose_name='Success Count')),
                ('fail_count', models.IntegerField(default=0, verbose_name='Fail Count')),
                ('error_count', models.IntegerField(default=0, verbose_name='Error Count')),
                ('task_id', models.CharField(blank=True, max_length=100, verbose_name='Celery Task ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_task_executions', to='api_environments.apienvironment', verbose_name='Environment')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_task_executions', to=settings.AUTH_USER_MODEL, verbose_name='Executed By')),
            ],
            options={
                'verbose_name': 'API Test Task Execution',
                'verbose_name_plural': 'API Test Task Executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestTaskCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='Status')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('duration', models.FloatField(default=0, verbose_name='Duration (seconds)')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_task_results', to='api_testcases.apitestreport', verbose_name='Test Report')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_task_results', to='api_testcases.apitestcase', verbose_name='Test Case')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_case_results', to='api_testtasks.apitesttaskexecution', verbose_name='Execution')),
            ],
            options={
                'verbose_name': 'API Test Task Case Result',
                'verbose_name_plural': 'API Test Task Case Results',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestTaskSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Suite Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priority', models.CharField(choices=[('P0', 'P0 - Critical'), ('P1', 'P1 - High'), ('P2', 'P2 - Normal'), ('P3', 'P3 - Low')], default='P2', max_length=2, verbose_name='Priority')),
                ('fail_fast', models.BooleanField(default=False, help_text='Stop executing subsequent cases when one fails', verbose_name='Fail Fast')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_test_task_suites_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_task_suites', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'API Test Task Suite',
                'verbose_name_plural': 'API Test Task Suites',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.AddField(
            model_name='apitesttaskexecution',
            name='task_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_executions', to='api_testtasks.apitesttasksuite', verbose_name='Task Suite'),
        ),
        migrations.CreateModel(
            name='ApiTestTaskCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Execution Order')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_task_cases', to='api_testcases.apitestcase', verbose_name='Test Case')),
                ('task_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_task_cases', to='api_testtasks.apitesttasksuite', verbose_name='Task Suite')),
            ],
            options={
                'verbose_name': 'API Test Task Case',
                'verbose_name_plural': 'API Test Task Cases',
                'ordering': ['order'],
                'unique_together': {('task_suite', 'testcase')},
            },
        ),
    ]
