# Generated by Codex on 2026-07-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testcases', '0005_apiinterfacecase_apiinterfacecasereport_and_more'),
        ('api_testtasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apitesttaskcase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='apitesttaskcase',
            name='case_type',
            field=models.CharField(
                choices=[
                    ('scenario', 'Scenario Case'),
                    ('interface', 'Interface Case'),
                ],
                default='scenario',
                max_length=20,
                verbose_name='Case Type',
            ),
        ),
        migrations.AlterField(
            model_name='apitesttaskcase',
            name='testcase',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='api_task_cases',
                to='api_testcases.apitestcase',
                verbose_name='Test Case',
            ),
        ),
        migrations.AddField(
            model_name='apitesttaskcase',
            name='interface_case',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='api_task_cases',
                to='api_testcases.apiinterfacecase',
                verbose_name='Interface Case',
            ),
        ),
        migrations.AddField(
            model_name='apitesttaskcaseresult',
            name='case_type',
            field=models.CharField(
                choices=[
                    ('scenario', 'Scenario Case'),
                    ('interface', 'Interface Case'),
                ],
                default='scenario',
                max_length=20,
                verbose_name='Case Type',
            ),
        ),
        migrations.AlterField(
            model_name='apitesttaskcaseresult',
            name='testcase',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='api_task_results',
                to='api_testcases.apitestcase',
                verbose_name='Test Case',
            ),
        ),
        migrations.AddField(
            model_name='apitesttaskcaseresult',
            name='interface_case',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='api_task_results',
                to='api_testcases.apiinterfacecase',
                verbose_name='Interface Case',
            ),
        ),
        migrations.AddField(
            model_name='apitesttaskcaseresult',
            name='interface_report',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='api_task_results',
                to='api_testcases.apiinterfacecasereport',
                verbose_name='Interface Case Report',
            ),
        ),
        migrations.AddConstraint(
            model_name='apitesttaskcase',
            constraint=models.UniqueConstraint(
                condition=models.Q(('testcase__isnull', False)),
                fields=('task_suite', 'testcase'),
                name='uniq_api_task_suite_case',
            ),
        ),
        migrations.AddConstraint(
            model_name='apitesttaskcase',
            constraint=models.UniqueConstraint(
                condition=models.Q(('interface_case__isnull', False)),
                fields=('task_suite', 'interface_case'),
                name='uniq_api_task_suite_iface_case',
            ),
        ),
        migrations.AddConstraint(
            model_name='apitesttaskcase',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ('case_type', 'scenario'),
                        ('interface_case__isnull', True),
                        ('testcase__isnull', False),
                    )
                    | models.Q(
                        ('case_type', 'interface'),
                        ('interface_case__isnull', False),
                        ('testcase__isnull', True),
                    )
                ),
                name='valid_api_task_case_target',
            ),
        ),
        migrations.AddConstraint(
            model_name='apitesttaskcaseresult',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ('case_type', 'scenario'),
                        ('interface_case__isnull', True),
                        ('testcase__isnull', False),
                    )
                    | models.Q(
                        ('case_type', 'interface'),
                        ('interface_case__isnull', False),
                        ('testcase__isnull', True),
                    )
                ),
                name='valid_api_task_result_target',
            ),
        ),
    ]
