# Generated by Django 5.2 on 2025-11-12 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestratorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField(verbose_name='需求描述')),
                ('knowledge_base_ids', models.JSONField(blank=True, default=list, verbose_name='知识库ID列表')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('requirement_analysis', models.JSONField(blank=True, null=True, verbose_name='需求分析结果')),
                ('knowledge_docs', models.JSONField(blank=True, default=list, verbose_name='检索的知识文档')),
                ('testcases', models.JSONField(blank=True, default=list, verbose_name='生成的测试用例')),
                ('execution_log', models.JSONField(blank=True, default=list, verbose_name='执行日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestrator_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '智能编排任务',
                'verbose_name_plural': '智能编排任务',
                'db_table': 'orchestrator_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
