# Generated by Django 5.2 on 2025-11-13 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_integration', '0003_add_chat_session_link'),
        ('projects', '0002_project_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orchestratortask',
            name='project',
            field=models.ForeignKey(default=1, help_text='任务必须关联到项目,用于数据隔离', on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='所属项目'),
            preserve_default=False,
        ),
    ]
