# Generated by Django 5.2 on 2025-11-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_integration', '0004_alter_orchestratortask_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orchestratortask',
            name='knowledge_base_ids',
        ),
    ]
