# Generated by Django 5.2 on 2025-12-02 03:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0012_change_context_limit_default'),
        ('orchestrator_integration', '0005_remove_knowledge_base_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(verbose_name='任务目标（用户原始请求）')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '执行中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('max_steps', models.IntegerField(default=50, verbose_name='最大步骤数')),
                ('current_step', models.IntegerField(default=0, verbose_name='当前步骤')),
                ('final_response', models.TextField(blank=True, verbose_name='最终响应')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to='langgraph_integration.chatsession', verbose_name='关联会话')),
            ],
            options={
                'verbose_name': 'Agent任务',
                'verbose_name_plural': 'Agent任务',
                'db_table': 'agent_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentBlackboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_summary', models.JSONField(default=list, verbose_name='历史摘要列表')),
                ('current_state', models.JSONField(default=dict, verbose_name='当前状态')),
                ('tool_results_refs', models.JSONField(default=list, verbose_name='工具结果引用')),
                ('context_variables', models.JSONField(default=dict, verbose_name='上下文变量')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blackboard', to='orchestrator_integration.agenttask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': 'Agent黑板',
                'verbose_name_plural': 'Agent黑板',
                'db_table': 'agent_blackboard',
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='步骤序号')),
                ('input_context', models.JSONField(default=dict, verbose_name='输入上下文（精简版）')),
                ('ai_thinking', models.TextField(blank=True, verbose_name='AI思考过程')),
                ('ai_decision', models.TextField(blank=True, verbose_name='AI决策')),
                ('tool_name', models.CharField(blank=True, max_length=100, verbose_name='工具名称')),
                ('tool_input', models.JSONField(blank=True, null=True, verbose_name='工具输入')),
                ('tool_output_summary', models.TextField(blank=True, verbose_name='工具输出摘要')),
                ('tool_output_full_ref', models.CharField(blank=True, max_length=200, verbose_name='完整输出引用')),
                ('ai_response', models.TextField(blank=True, verbose_name='AI响应')),
                ('is_final', models.BooleanField(default=False, verbose_name='是否为最终响应')),
                ('token_input', models.IntegerField(default=0, verbose_name='输入Token数')),
                ('token_output', models.IntegerField(default=0, verbose_name='输出Token数')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(毫秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='orchestrator_integration.agenttask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': 'Agent步骤',
                'verbose_name_plural': 'Agent步骤',
                'db_table': 'agent_step',
                'ordering': ['task', 'step_number'],
                'unique_together': {('task', 'step_number')},
            },
        ),
    ]
