# Generated by Django 5.2 on 2025-12-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_integration', '0006_agenttask_agentblackboard_agentstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='max_steps',
            field=models.IntegerField(default=500, verbose_name='最大步骤数'),
        ),
    ]
