# Generated by Django 5.2 on 2026-01-17 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_integration', '0007_change_max_steps_default_500'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Agent 名称')),
                ('tool_name', models.CharField(help_text='英文标识符，唯一，用于 LLM Tool Calling（如 analyze_requirement）', max_length=100, unique=True, verbose_name='Tool 名称')),
                ('description', models.TextField(help_text='LLM 根据此描述决定是否调用此 Agent，需清晰说明用途和输入输出', verbose_name='Tool 描述')),
                ('system_prompt', models.TextField(help_text='Agent 的 system prompt，定义 Agent 的角色和行为', verbose_name='系统提示词')),
                ('allowed_tools', models.JSONField(blank=True, default=list, help_text='此 Agent 可以使用的 MCP 工具名列表，如 ["search_knowledge_base", "execute_script"]', verbose_name='允许的 MCP 工具')),
                ('include_knowledge_base', models.BooleanField(default=True, help_text='是否自动添加知识库搜索工具', verbose_name='包含知识库工具')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(default=0, help_text='数值越小越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(blank=True, help_text='为空表示全局 Agent，所有项目可用', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'Agent 配置',
                'verbose_name_plural': 'Agent 配置',
                'db_table': 'orchestrator_agent_config',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
