# Generated by Django 5.2 on 2026-01-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_integration', '0009_add_default_agents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentConfig',
        ),
    ]
