# Generated by Django 5.1.4 on 2025-05-25 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteMCPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='远程 MCP 服务器的名称', max_length=255, unique=True)),
                ('url', models.URLField(help_text='远程 MCP 服务器的 URL', max_length=2048)),
                ('headers', models.JSONField(blank=True, default=dict, help_text="可选的认证头，例如 {'Authorization': 'Bearer YOUR_TOKEN'}")),
                ('is_active', models.BooleanField(default=True, help_text='是否启用此远程 MCP 服务器')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='此远程 MCP 配置的拥有者', on_delete=django.db.models.deletion.CASCADE, related_name='remote_mcp_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '远程 MCP 配置',
                'verbose_name_plural': '远程 MCP 配置',
                'ordering': ['name'],
            },
        ),
    ]
