# Generated by Django 5.1.4 on 2025-05-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotemcpconfig',
            name='transport',
            field=models.CharField(default='streamable-http', help_text="MCP 服务器的传输协议，例如 'streamable-http'", max_length=50),
        ),
    ]
