# Generated by Django 5.2 on 2025-11-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_tools', '0002_remotemcpconfig_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotemcpconfig',
            name='url',
            field=models.CharField(help_text='远程 MCP 服务器的 URL', max_length=2048),
        ),
    ]
