# Generated by Django 5.2 on 2026-01-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_tools', '0005_remove_project_make_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotemcpconfig',
            name='hitl_tools',
            field=models.JSONField(blank=True, default=list, help_text="需要人工审批的工具列表（为空时表示所有工具），例如 ['playwright_click', 'playwright_fill']"),
        ),
        migrations.AddField(
            model_name='remotemcpconfig',
            name='require_hitl',
            field=models.BooleanField(default=False, help_text='是否对该 MCP 的所有工具启用人工审批'),
        ),
    ]
