# Generated by Django 5.2 on 2026-01-16 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_tools', '0006_add_hitl_config_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='工具名称', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='工具描述')),
                ('input_schema', models.JSONField(blank=True, default=dict, help_text='工具的输入参数 JSON Schema')),
                ('require_hitl', models.BooleanField(blank=True, default=None, help_text='是否需要人工审批（None 表示继承 MCP 配置）', null=True)),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='上次同步时间')),
                ('mcp_config', models.ForeignKey(help_text='关联的 MCP 配置', on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='mcp_tools.remotemcpconfig')),
            ],
            options={
                'verbose_name': 'MCP 工具',
                'verbose_name_plural': 'MCP 工具',
                'ordering': ['mcp_config', 'name'],
                'unique_together': {('mcp_config', 'name')},
            },
        ),
    ]
