# Generated by Django 5.2 on 2026-05-26 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='用户名')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('path', models.CharField(max_length=255, verbose_name='请求路径')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='操作模块')),
                ('action', models.CharField(blank=True, max_length=255, verbose_name='操作描述')),
                ('request_data', models.TextField(blank=True, verbose_name='请求数据')),
                ('response_code', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('response_data', models.TextField(blank=True, verbose_name='响应数据')),
                ('duration', models.IntegerField(default=0, verbose_name='执行耗时(毫秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
