# Generated by Django 5.2 on 2025-07-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewreport",
            name="clarity_score",
            field=models.IntegerField(
                default=0, help_text="0-100分", verbose_name="清晰度评分"
            ),
        ),
        migrations.AddField(
            model_name="reviewreport",
            name="completeness_score",
            field=models.IntegerField(
                default=0, help_text="0-100分", verbose_name="完整性评分"
            ),
        ),
        migrations.AddField(
            model_name="reviewreport",
            name="consistency_score",
            field=models.IntegerField(
                default=0, help_text="0-100分", verbose_name="一致性评分"
            ),
        ),
        migrations.AddField(
            model_name="reviewreport",
            name="review_type",
            field=models.CharField(
                choices=[("direct", "直接评审"), ("comprehensive", "全面评审")],
                default="comprehensive",
                max_length=20,
                verbose_name="评审类型",
            ),
        ),
    ]
