# Generated by Django 5.2 on 2025-11-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_reviewreport_clarity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreport',
            name='specialized_analyses',
            field=models.JSONField(blank=True, default=dict, help_text='存储完整性、一致性、可测性、可行性、清晰度5个专项分析的详细结果', verbose_name='专项分析详情'),
        ),
    ]
