# Generated by manual creation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_reviewreport_specialized_analyses'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreport',
            name='testability_score',
            field=models.IntegerField(default=0, help_text='0-100分', verbose_name='可测性评分'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='feasibility_score',
            field=models.IntegerField(default=0, help_text='0-100分', verbose_name='可行性评分'),
        ),
    ]
