# Generated by Django 5.2 on 2026-01-10 03:17

import django.db.models.deletion
import requirements.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0004_reviewreport_feasibility_testability_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementdocument',
            name='has_images',
            field=models.BooleanField(default=False, verbose_name='包含图片'),
        ),
        migrations.AddField(
            model_name='requirementdocument',
            name='image_count',
            field=models.IntegerField(default=0, verbose_name='图片数量'),
        ),
        migrations.AlterField(
            model_name='requirementdocument',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word文档'), ('docx', 'Word文档'), ('txt', '文本文件'), ('md', 'Markdown')], max_length=10, verbose_name='文档类型'),
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to=requirements.models.document_image_upload_path, verbose_name='图片文件')),
                ('image_id', models.CharField(help_text='如 img_001，用于占位符匹配', max_length=50, verbose_name='图片ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('content_type', models.CharField(default='image/png', max_length=100, verbose_name='MIME类型')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='宽度')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='高度')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='requirements.requirementdocument', verbose_name='所属文档')),
            ],
            options={
                'verbose_name': '文档图片',
                'verbose_name_plural': '文档图片',
                'ordering': ['document', 'order'],
                'indexes': [models.Index(fields=['document', 'order'], name='requirement_documen_8f6d17_idx'), models.Index(fields=['document', 'image_id'], name='requirement_documen_387943_idx')],
            },
        ),
    ]
