# Generated by Django 5.2 on 2026-01-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_add_document_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreport',
            name='logic_score',
            field=models.IntegerField(default=0, help_text='0-100分', verbose_name='逻辑分析评分'),
        ),
        migrations.AlterField(
            model_name='reviewissue',
            name='issue_type',
            field=models.CharField(choices=[('specification', '规范性'), ('clarity', '清晰度'), ('completeness', '完整性'), ('consistency', '一致性'), ('feasibility', '可行性'), ('logic', '逻辑性')], max_length=20, verbose_name='问题类型'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='specialized_analyses',
            field=models.JSONField(blank=True, default=dict, help_text='存储完整性、一致性、可测性、可行性、清晰度、逻辑分析6个专项分析的详细结果', verbose_name='专项分析详情'),
        ),
    ]
