# Generated by Django 5.2 on 2026-01-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0007_add_review_progress_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreport',
            name='progress',
            field=models.FloatField(default=0, help_text='0-1小数', verbose_name='评审进度'),
        ),
    ]
