# Generated by Codex
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import file_management.models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=512, upload_to=file_management.models.managed_file_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, max_length=32)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('available', '可用'), ('processing', '处理中'), ('broken', '损坏'), ('deleted', '已删除')], default='available', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_files', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_files', to='projects.project')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='FileReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(choices=[('api_interface', '接口'), ('api_testcase', '接口用例'), ('ui_testcase', 'UI用例'), ('ui_page_steps', 'UI页面步骤'), ('llm_chat', 'LLM对话')], max_length=50)),
                ('ref_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_references', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='file_management.fileasset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_references', to='projects.project')),
            ],
            options={'unique_together': {('file', 'ref_type', 'ref_id')}},
        ),
        migrations.AddIndex(model_name='fileasset', index=models.Index(fields=['project', 'status', 'is_deleted'], name='file_manage_project_4da046_idx')),
        migrations.AddIndex(model_name='fileasset', index=models.Index(fields=['project', 'original_name'], name='file_manage_project_e79493_idx')),
        migrations.AddIndex(model_name='fileasset', index=models.Index(fields=['created_at'], name='file_manage_created_160bc9_idx')),
        migrations.AddIndex(model_name='filereference', index=models.Index(fields=['project', 'ref_type', 'ref_id'], name='file_manage_project_e82a69_idx')),
        migrations.AddIndex(model_name='filereference', index=models.Index(fields=['file', 'ref_type'], name='file_manage_file_id_f9f4d6_idx')),
    ]
