# Generated by Codex
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('file_management', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManagementSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_delete_on_unbind', models.BooleanField(default=False)),
                ('auto_delete_zero_refs', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_management_setting', to='projects.project')),
            ],
            options={
                'verbose_name': '文件管理设置',
                'verbose_name_plural': '文件管理设置',
                'db_table': 'file_management_setting',
            },
        ),
    ]
