# Generated by Django 5.2 on 2026-07-01 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_filemanagementsetting'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fileasset',
            name='file_manage_project_4da046_idx',
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['project', 'is_deleted', 'status'], name='file_manage_project_695f14_idx'),
        ),
    ]
