# Generated by Django 5.2 on 2026-07-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_remove_fileasset_file_manage_project_4da046_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filereference',
            name='ref_type',
            field=models.CharField(choices=[('api_interface', '接口'), ('api_testcase', '测试用例'), ('api_interface_case', '接口用例'), ('ui_testcase', 'UI用例'), ('ui_page_steps', 'UI页面步骤'), ('llm_chat', 'LLM对话')], max_length=50),
        ),
    ]
